### ISSUE TITLE
I can't seem to get this to work

### ISSUE THREAD

**Issue by ShimShamSam** [pbastowski/ecmascript-extras#2]
I keep getting the same errors as if I hadn't installed the package at all. Specifically, it's failing on async function definitions. I even copied your .babelrc settings into my root directory but it made no difference.

**Comment by pbastowski** [comment]
Exactly what error message do you get in your browser dev console?

**Comment by pbastowski** [comment]
Are you able to use `pbastowski:angular-babel` instead of the Meteor 1.2 `ecmascript` package? My angular-babel package does support async functions properly, whereas Meteor's `ecmascript` package is a subset of Babel and for my purposes is missing valuable features.

I created `ecmascript-extras` as an experiment to see if it would be possible to "polyfill" the missing stuff, but now I think it is better to replace that package entirely with one that does what I want it to do. So, I'm leaning towards retiring the `ecmascript-extras` package due to various compatibility issues.

Could you please try 

```
meteor add pbastowski:angular-babel
```

followed by

```
meteor remove ecmascript pbastowski:ecmascript-extras
```

And then let me know if that helped you.

**Comment by ShimShamSam** [comment]
It worked, but since your package is a fork of grigio:babel and since I'm not using Angular, I think I'll just stick with grigio's package for now.

**Comment by pbastowski** [comment]
Although my package was a fork of grigio's for Meteor 1.1, it is no longer the case for Meteor 1.2. The Meteor 1.2 version includes a new build plugin architecture with caching, which was not available in previous Meteor versions. The Angular part is just running `ng-annotate` on the code transpiled by Babel and will not hurt any of your code :)

**Comment by ShimShamSam** [comment]
Ah, using Meteor's new plugin architecture allows your package to work on regular .js files :)
